### ISSUE TITLE
Why is MRMO on this list?

### ISSUE THREAD

**Issue by FocalFlare** [ErikMcClure/bad-licenses#20]
No shade, but people are allowed to make certain aspects about their own material available. Mrmo made it clear that they didn't want their tool "MRMO-HALFTONE" to be used for NFT's or anything crypto-related. So, it's at least better for you to respect people's decisions on making things available for certain aspects instead of calling them out for not making it fully available (at least be happy that it's available and you can use it).

Again, I don't mean to be rude or anything (and don't take this the wrong way), but doing stuff like this is just immature.

**Comment by ErikMcClure** [comment]
I clarified that the **intent** is not the issue here in https://github.com/ErikMcClure/bad-licenses/commit/e948021240eee08a5efee96f0fedd8c6a90acf6a, it's the language being used. For example, Git is based on a merkle tree where the hashes of each successive commit need to be based on the previous hash of the previous commit. This could be considered a "blockchain", minus proof of work. Because there is no legal definition of "blockchain", you could sue anyone using Git for this, including the author of the license themselves. Likewise, NFTs are not actually well-defined. The concept of an NFT is different from the scams being implemented on smart contracts are the actual thing people have issues with.

The reason licenses get into the "bad licenses" club is because they try to use non-legal terms in a legal context, because they are written by programmers instead of lawyers.
